### ISSUE TITLE
Translate for non-default language only passes the first argument to buildString

### ISSUE THREAD

**Issue by shawncplus** [AGROSICA/node-localize#1]
The slice on https://github.com/AGROSICA/node-localize/blob/master/lib/localize.js#L201 is only grabbing the first argument to translate.

So translate("$[1] blah $[2]", "goodsubstitute", "badsubstitute") gets built as "goodsubstitute blah $[2]"

**Comment by shawncplus** [comment]
whoops, that's a splice not a slice. Either way it still doesn't work

**Comment by dfellis** [comment]
Good catch, and good timing. I just got internet access again after the holidays.

This looks like it should be a quick fix. :)

**Comment by dfellis** [comment]
Okay, that should do it. Let me know if it works for you, too, and I'll close this issue.

**Comment by shawncplus** [comment]
Hooray for awesome response time. Thankee sai.

**Comment by shawncplus** [comment]
I does indeed.
